name: Deploy Microservices via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push user-service
        run: |
          docker build -t fayiz007/user-service:v1 user-service
          docker push fayiz007/user-service:v1

      - name: Build & Push order-service
        run: |
          docker build -t fayiz007/order-service:v1 order-service
          docker push fayiz007/order-service:v1

      - name: Build & Push frontend
        run: |
          docker build -t fayiz007/frontend:v1 frontend
          docker push fayiz007/frontend:v1

      - name: Deploy to Kubernetes via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/deployer/microservices
            kubectl apply -f k8s/

